version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Map your Node.js app's port to host
    depends_on:
      - mongodb
    environment:
      MONGO_URL: mongodb://mongodb:27017/mydoc

  mongodb:
    image: mongo:4.4
    container_name: mongodb
    ports:
        - "27017:27017"
    volumes:
      - ./data:/data/db
